# Generated by Django 5.2.3 on 2025-08-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_registrosdiarios_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosdiarios',
            name='datecompleted',
        ),
        migrations.AddField(
            model_name='registrosdiarios',
            name='stress_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
